version: 2.1.{build}
environment:
  COVERALLS_REPO_TOKEN:
    secure: XNbT3F6G4V7AegyGBZZPQ5cOEtic5P6OJUXd9K2wmj3mGXmQsJezis8oz9/vzDLq
pull_requests:
  do_not_increment_build_number: true
configuration: Release
platform: Any CPU
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
before_build:
- nuget restore src\stashbox.decoratorextension.sln
- nuget update src\stashbox.decoratorextension.sln -id Stashbox -id Sendstorm
build:
  project: src\stashbox.decoratorextension.sln
  publish_nuget: true
  publish_nuget_symbols: false
  include_nuget_references: true
  parallel: true
  verbosity: normal
test_script:
- ps: . .\coverage.ps1
notifications:
- provider: Email
  to:
  - peter.csajtai@outlook.com
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: true